name: gloss-to-gif

dependencies:
- active
- base
- gloss
- gloss-export

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - JuicyPixels
      - bytestring
      - filepath
      - gloss-to-gif
      - tasty
      - tasty-hunit
      - template-haskell
      - th-utilities
