name: gloss-to-gif

dependencies:
- JuicyPixels
- active
- base
- bytestring
- containers
- gloss
- gloss-active
- gloss-export
- gloss-juicy

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - filepath
      - gloss-to-gif
      - tasty
      - tasty-hunit
      - template-haskell
      - th-utilities
