resolver: lts-10.3
packages:
  - animated-tiling
  - face-trace
  - face-up
  - face-down
  - gloss-to-gif
extra-deps:
  - git: git@github.com:acowley/ffmpeg-light.git
    commit: 05f4dfe2b695c0f4ce0e63a9c5320ed4efd74fee
  - acid-state-0.14.3
  - gloss-export-0.1.0.2
  - gloss-juicy-0.2.2
