name: animated-tiling

dependencies:
- active
- base
- gloss
- gloss-export
- gloss-juicy
- gloss-to-gif
- lens
- linear

ghc-options:
  - -Wall

library:
  source-dirs: src

tests:
  test:
    source-dirs: test
    main: Main.hs
    dependencies:
      - animated-tiling
      - filepath
      - tasty
      - tasty-golden
      - template-haskell
      - th-utilities
