name: gloss-active

dependencies:
- active
- base
- containers
- gloss

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  pulsating-circle:
    main: main.hs
    source-dirs: pulsating-circle
    dependencies:
      - gloss-active
      - gloss-active-test-support
