name: face-trace

dependencies:
  - JuicyPixels
  - acid-state
  - async
  - base
  - containers
  - directory
  - extra
  - ffmpeg-light
  - filepath
  - gloss
  - gloss-juicy
  - lens
  - linear
  - mmorph
  - mtl
  - safecopy
  - smoothie
  - stm
  - transformers

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  face-trace:
    main: main.hs
    source-dirs: app
    dependencies:
      - face-trace
      - optparse-generic
    ghc-options:
      - -threaded
      - "-with-rtsopts -N"
