name: face-trace

dependencies:
  - JuicyPixels
  - base
  - ffmpeg-light
  - gloss
  - gloss-juicy
  - lens

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  face-trace:
    main: main.hs
    source-dirs: app
    dependencies:
      - face-trace
      - optparse-generic
