name: face-up

dependencies:
  - JuicyPixels
  - base
  - ffmpeg-light
  - gloss
  - gloss-juicy
  - lens

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  face-up:
    main: main.hs
    source-dirs: app
    dependencies:
      - face-up
      - optparse-generic
