name: face-up

dependencies:
  - base
  - ffmpeg-light

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  face-up:
    main: main.hs
    source-dirs: app
    dependencies:
      - JuicyPixels
      - gloss
      - gloss-juicy
      - lens
      - optparse-generic
