name: face-down

dependencies:
  - acid-state
  - base
  - face-trace
  - ffmpeg-light
  - gloss-rendering

ghc-options:
  - -Wall

library:
  source-dirs: src

executables:
  face-down:
    main: main.hs
    source-dirs: app
    dependencies:
      - face-trace
      - optparse-generic
